# Generated by Django 4.1.4 on 2022-12-30 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 30, 16, 33, 35, 771310), null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 30, 16, 33, 35, 771310), null=True),
        ),
    ]
