# Generated by Django 4.1.4 on 2022-12-30 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_alter_contract_end_date_alter_contract_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 30, 16, 35, 37, 919486), null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 30, 16, 35, 37, 919486), null=True),
        ),
    ]
