# Generated by Django 4.1.4 on 2022-12-29 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(max_length=25)),
                ('owner', models.CharField(max_length=50)),
                ('tenant', models.CharField(max_length=50)),
                ('floor', models.IntegerField(max_length=2)),
                ('floor_count', models.IntegerField(max_length=2)),
                ('room_count', models.IntegerField(max_length=1)),
                ('area', models.IntegerField(max_length=4)),
                ('phone', models.IntegerField(max_length=11)),
                ('rent_price', models.IntegerField(max_length=4)),
                ('mortgage_price', models.IntegerField(max_length=4)),
                ('sell_price', models.IntegerField(max_length=4)),
                ('apartmentStatuses', models.CharField(choices=[('rent', 'Rent'), ('sell', 'Sell')], max_length=15)),
                ('phoneStatuses', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=15)),
                ('address_aprtment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Address', to='address.address', verbose_name='apertment_id')),
            ],
            options={
                'verbose_name': 'کاربر',
            },
        ),
    ]
