# Generated by Django 4.1.4 on 2022-12-29 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartemant', '0003_apartment_end_date_apartment_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='end_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 29, 11, 47, 35, 313169), null=True),
        ),
    ]
