# Generated by Django 4.1.4 on 2022-12-30 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartemant', '0007_alter_apartment_end_date_alter_apartment_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='apartmentStatuses',
            field=models.CharField(choices=[('rent', 'Rent'), ('sell', 'Sell'), ('inactive', 'Inactive')], max_length=15),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 30, 16, 33, 35, 725520), null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 30, 16, 33, 35, 725520), null=True),
        ),
    ]
