# Generated by Django 4.1.4 on 2022-12-30 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartemant', '0008_alter_apartment_apartmentstatuses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='start_date',
        ),
    ]
