# Generated by Django 4.1.4 on 2022-12-29 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_house_end_date_house_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 29, 11, 47, 35, 307187)),
        ),
        migrations.AlterField(
            model_name='house',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 29, 11, 47, 35, 307187)),
        ),
    ]
