# Generated by Django 4.1.4 on 2022-12-30 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_house_end_date_alter_house_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='house',
            name='start_date',
        ),
    ]
