# Generated by Django 4.1.4 on 2022-12-29 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=25)),
                ('area', models.IntegerField()),
                ('phone', models.CharField(max_length=11)),
                ('rent_price', models.CharField(max_length=25)),
                ('mortgage_price', models.CharField(max_length=25)),
                ('sell_price', models.CharField(max_length=25)),
                ('shopStatuses', models.CharField(choices=[('rent', 'Rent'), ('sell', 'Sell')], max_length=15)),
                ('phoneStatuses', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=15)),
                ('address_aprtment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_address', to='address.address', verbose_name='apertment_id')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_owner_user', to='user.user', verbose_name='owner_id')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_tenant_user', to='user.user', verbose_name='tenant_id')),
            ],
        ),
    ]
