# Generated by Django 4.1.4 on 2022-12-29 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_end_date_shop_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 29, 11, 49, 20, 209125), null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 29, 11, 49, 20, 209125), null=True),
        ),
    ]
