# Generated by Django 4.1.4 on 2022-12-30 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_shop_end_date_alter_shop_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 30, 16, 33, 35, 755077), null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 30, 16, 33, 35, 755077), null=True),
        ),
    ]
